[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Nested check
[[patches]]
[patches.module]
source = "setup.lua"
before = "main.lua"
name = "mtgamble.setup"

# Add Colorless cards to decks, and Double Red/Black to Checkered Deck
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'if self.GAME.starting_params.extra_cards then'
position = 'before'
match_indent = true
payload = '''
local mtg_colorless_dupes = {
   ["Red Deck"] = 3,
   ["Blue Deck"] = 3,
   ["Yellow Deck"] = 3,
   ["Green Deck"] = 3,
   ["Black Deck"] = 3,
   ["Magic Deck"] = 2,
   ["Nebula Deck"] = 2,
   ["Ghost Deck"] = 2,
   ["Zodiac Deck"] = 1,
   ["Anaglyph Deck"] = 1,
   ["Plasma Deck"] = 2,
}
local mtg_colorless_to_add = mtg_colorless_dupes[G.GAME.selected_back_key.name]
if mtg_colorless_to_add then
   for k, v in pairs(self.P_CARDS) do
      local _r, _s = SMODS.Ranks[v.value].card_key, SMODS.Suits[v.suit].card_key
      if _s == 'mtg_Colorless' then
         for i=1, mtg_colorless_to_add do
            card_protos[#card_protos+1] = {s=_s,r=_r,e=_de and _de.enhancement,d=_de and _de.edition,g=_de and _de.gold_seal}
         end
      end
   end
end

if G.GAME.selected_back_key.name == "Checkered Deck" then
   for k, v in pairs(self.P_CARDS) do
      local _r, _s = SMODS.Ranks[v.value].card_key, SMODS.Suits[v.suit].card_key
      if _s == 'mtg_Black' or _s == 'mtg_Red' then
         card_protos[#card_protos+1] = {s=_s,r=_r,e=_de and _de.enhancement,d=_de and _de.edition,g=_de and _de.gold_seal}
      end
   end
end

'''

