[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Nested check
[[patches]]
[patches.module]
source = "setup.lua"
before = "main.lua"
name = "mtgamble.setup"

# Add Colorless cards to decks, and Double Red/Black to Checkered Deck
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'if self.GAME.starting_params.extra_cards then'
position = 'before'
match_indent = true
payload = '''
if SMODS.Mods and SMODS.Mods['MountGamble'] then
   SMODS.Mods['MountGamble'].addAdditionalCards(card_protos, _de)
end

'''

